server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
            - Method=GET,POST
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**,/locations/**
            - Method=GET,POST
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET,POST
eureka:
  instance:
    prefer-ip-address: true
    #allow to use IP address for eureka server discovery
  client:
    fetch-registry: true
    #allow this service to fetch eureka server
    register-with-eureka: true
    #will make the service a eureka client
    service-url:
      defaultZone: http://localhost:8761/eureka
    #defining the eureka server location